#!/usr/bin/env zsh

############################
###  build the C/C++ part
############################

pushd $JXL_root_DIR/build

	if [[ ! -z $1 ]]
	then
		build_dir=$JXL_root_DIR/build/native_$1
		source_dir=$JXL_root_DIR/repo/libjxl_$1
	else
		build_dir=$JXL_root_DIR/build/native
		source_dir=$JXL_root_DIR/repo/libjxl
	fi

	if [[ -d $build_dir ]]
	then
		rm -rf $build_dir
	fi

	mkdir ${build_dir}

	pushd ${build_dir}
		cmake -DCMAKE_CXX_FLAGS="-march=native -mtune=native" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF $source_dir
		cmake --build . -- -j$(nproc)
	popd
popd
