#!/usr/bin/env zsh

############################
###  build the C/C++ part
############################

pushd $JXL_root_DIR/build

	# $1 native or generic
	# $2 commit number, HEAD is used if none

	if [[ ! -z $2 ]]
	then
		build_dir=$JXL_root_DIR/build/libjxl_$1_$2
		source_dir=$JXL_root_DIR/repo/libjxl_$2
	else
		build_dir=$JXL_root_DIR/build/libjxl_$1
		source_dir=$JXL_root_DIR/repo/libjxl
	fi

	if [[ -d $build_dir ]]
	then
		rm -rf $build_dir
	fi

	mkdir ${build_dir}

	pushd ${build_dir}
		case $1 in 
			'native')
				cmake -DCMAKE_CXX_FLAGS="-O3 -march=native -mtune=native" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_DEVTOOLS=ON $source_dir
				;;
			'generic')
				cmake -DCMAKE_CXX_FLAGS="-march=x86-64 -mtune=generic" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_DEVTOOLS=ON $source_dir
				;;
			*)
				echo "you must specify native or generic"
				return 1
				;;
		esac
		
		cmake --build . -- -j$(nproc)
	popd

popd
